---
abstract: 'Uniform Resource Identifiers (absolute and relative)'
author:
  - 'Gisle Aas <gisle@activestate.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Temp: '0'
  Test: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: URI
no_index:
  directory:
    - t
    - inc
recommends:
  Business::ISBN: '0'
requires:
  MIME::Base64: '2'
  perl: '5.008001'
resources:
  MailingList: mailto:libwww@perl.org
  repository: https://github.com/libwww-perl/uri
version: '1.61'
